### ISSUE TITLE
我想把一些素材在本地加密后放到我的kaggle端的sd中，sd端无法解密图片

### ISSUE THREAD

**Issue by RebortQu** [viyiviyi/encrypt_gallery#1]
打开软件，填写目录，填写和kaggle端sd中一样的密码，然后在sd端无法解密。在本地用软件也无法解密

**Comment by viyiviyi** [comment]
如果你的图片不是png格式导致出现的这个问题，在1.1.6版本得到修复了
[https://github.com/viyiviyi/encrypt_gallery/releases/tag/1.1.6](https://github.com/viyiviyi/encrypt_gallery/releases/tag/1.1.6)

**Comment by RebortQu** [comment]
> 如果你的图片不是png格式导致出现的这个问题，在1.1.6版本得到修复了 https://github.com/viyiviyi/encrypt_gallery/releases/tag/1.1.6
是png的，我下载来看看

**Comment by RebortQu** [comment]
> 如果你的图片不是png格式导致出现的这个问题，在1.1.6版本得到修复了 https://github.com/viyiviyi/encrypt_gallery/releases/tag/1.1.6

是1.1.6.1吗

**Comment by viyiviyi** [comment]
> > 如果你的图片不是png格式导致出现的这个问题，在1.1.6版本得到修复了 https://github.com/viyiviyi/encrypt_gallery/releases/tag/1.1.6
> 
> 是1.1.6.1吗

是的，1.1.6.1。而且，如果是png图片解密后没有图片，也可能是密码错误之类的。如果能在软件里浏览到正常的图片，那肯定是能解密的。
